baseURL = "https://manchestermn.gov/"
languageCode = "en-us"
title = "City of Manchester"
theme = "universal"

[params]
    disabled_logo = true
    logo_text = "City of Manchester"
    contact_url = "/contact"
    address =   """ <p class="text-uppercase"><strong>City of Manchester</strong>
                    <br>144 McKinley Street
                    <br>Manchester, MN 56007
                    <br>
                    <br><a href="mailto:cityofmanchester1@outlook.com">Email US</a>
                    <br>        
                    </p>
                """
    enableGoogleMaps = false
    latitude = "43.724093"
    longitude = "-93.452566"
    copyright = "© Copyright 2024 City of Manchester MN"
    date_format = "January 2, 2006"

[[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/news/"
    weight     = 4

[[menu.main]]
    name       = "Legislation"
    identifier = "menu.legislation"
    url        = "/"
    weight     = 5

[[menu.main]]
    name       = "Ordinances"
    url        = "/ordinances/"
    weight     = 1
    parent     = "menu.legislation"

[[menu.main]]
    name       = "Resolutions"
    url        = "/resolutions/"
    weight     = 2
    parent     = "menu.legislation"

[[menu.main]]
    name       = "Fee Schedule"
    url        = "/feeschedule/"
    weight     = 3
    parent     = "menu.legislation"

[[menu.main]]
    identifier = "utilities"
    name       = "Utilities"
    url        = "/utilities/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7