baseURL = "https://manchestermn.gov/"
languageCode = "en-us"
title = "City of Manchester MN"
theme = ["hugo-embed-pdf-shortcode", "universal"]
googleAnalytics = "G-XP04JJLY0V"
enableInlineShortcodes = true

[params]
    enableRobotsTXT = true
    disabled_logo = true
    logo_text = "City of Manchester MN"
    contact_url = "/contact"
    address =   """ <p class="text-uppercase"><strong>City of Manchester</strong>
                    <br>144 McKinley Street
                    <br>Manchester, MN 56007
                    <br>
                    <br><a href="mailto:cityofmanchester1@outlook.com">Email US</a>
                    <br>
                    </p>
                """
    enableGoogleMaps = false
    googleMapsApiKey = ""
    latitude = "43.7241891"
    longitude = "-93.4526438"
    copyright = "Copyright 2025 City of Manchester MN"
    date_format = "January 2, 2006"
    defaultKeywords = ["manchester", "minnesota", "mn", "city", "56007"]
    defaultDescription = "City of Manchester MN"

[params.widgets]
    search = false
    categories = true
    tags = true

[params.recent_posts]
    enable = true
    title = "Recent News"

[params.footer.recent_posts]
    enable = false

[[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/news/"
    weight     = 4

[[menu.main]]
    name       = "ordinances"
    identifier = "Ordinances"
    url        = "/ordinances/"
    weight     = 5

[[menu.main]]
    identifier = "utilities"
    name       = "Utilities"
    url        = "/utilities/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7