baseURL = 'https://manchestermn.gov/'
languageCode = 'en-us'
title = 'City of Manchester'
theme = 'universal'
style = 'red'

[params]
    disabled_logo = true
    logo_text = "City of Manchester"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>City of Manchester</strong>
        <br>144 McKinley Street
        <br>Manchester, MN 56007
        <br>
        <br><a href="mailto:cityofmanchester1@outlook.com">Email US</a>
        <br>        
      </p>
      """
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"
    latitude = "43.724093"
    longitude = "-93.452566"
    copyright = "Copyright (C) 2024"

[[menu.main]]
    identifier = "ordinances"
    name       = "City Ordinances"
    url        = "/ordinances/"
    weight     = 6

[[menu.main]]
    identifier = "utilities"
    name       = "Utilities"
    url        = "/utilities/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7